### ISSUE TITLE
Cutting off-by-one error with selection=exclusive setting

### ISSUE THREAD

**Issue by louwers** [svermeulen/vim-easyclip#107]
`m` consistently doesn't cut the last character of what needed to be cut with the the `selection` option set to `exclusive`.

To reproduce:

```
ihello world<Esc>0
:set selection=exclusive<CR>
m$
```

## Expected result

```
```

## Actual result

```
d
```

**Comment by nkgm** [comment]
I've had the same problem with other plugins. It almost feels like `exclusive` was never meant to be used, or the great vimmers out there have good reason not to use it. I've been experimenting with `exclusive` and `onemore` checking how well they play with motions and visual, but with the overall lack of support it's starting to feel like a bad idea.

**Comment by svermeulen** [comment]
I think this is fixed now
