### ISSUE TITLE
Recent code changes break mm/m

### ISSUE THREAD

**Issue by flipjs** [svermeulen/vim-easyclip#117]
I've been using this for more than a year now with no issues. Recently I've noticed that when I create a new buffer with `:enew`, it seems EasyClip is not running or stops running. `mm` or `m` doesn't work at all. Its the same when I run neovim with a new file (e.g. `nvim new-file.txt`) or just start neovim and start typing, `mm` doesn't work.

The work around for this is the file has to exist first, like for example `touch new-file.txt && vim new-file.txt`, then everything is working fine.

I now reverted back to commit 9f29436 and `mm/m` is back working again.

**Comment by flipjs** [comment]
Related issue: #116

**Comment by svermeulen** [comment]
Ok I've reverted back to 9f29436 for now.  Although I am not seeing these issues on my set up, the breakage sounds worse than the features added in that PR (sorry @eloytoro).  Not sure if it's worth fixing or just abandoning the change completely but we'll leave it at 9f29436 for now

Please try again and close if fixed

**Comment by flipjs** [comment]
Can confirm its working again. Thank you!
