### ISSUE TITLE
Is this plugin deprecated by the replacements (vim-yoink etc.) for modern versions of vim/nvim?

### ISSUE THREAD

**Issue by infokiller** [svermeulen/vim-easyclip#128]
Hi,

For vim 8+ and nvim 0.4+ would you recommend I use the new plugins (yoink, cutless, subversive)?
It seems like this is what the README implies but it wasn't clear to me so I wanted to verify it.

Thanks!

**Comment by svermeulen** [comment]
Yes, I would suggest the newer plugins, since these will be more actively maintained going forward
