### ISSUE TITLE
Pasting over the last column not in the last line does not work properly in Visual mode

### ISSUE THREAD

**Issue by Coacher** [svermeulen/vim-easyclip#38]
Hello.

Consider the following file:
```
line one
line two
```
First use `vey` to yank the word 'line' from the first line.
Then use `<End>` to move the cursor to the end of the line.
Now use `vFi` to select the text up to the character 'i' and use either `P` or `p` to paste.
The resulting file is:
```
linel
line two
```
Expected results are:
```
lline
line two
```

This issue is related to the issue #36 and happens because of the similar reason.
Again, the problem is in `EasyClip#Paste#PasteTextVisualMode` function. In my use case it follows the `else` branch. And here's what happens:
1. Last character(s) is deleted via `"_d` since it is the current selection
2. `EasyClip#Paste#PasteText` is called with `P` as operator, which makes paste prepend the yanked text before the new last character.

Fix: detect whether we are on the last column and use `p` as operator in this case. I will create a pull request in a couple of minutes.

**Comment by svermeulen** [comment]
Yep, I see what you mean - it's the same issue except for column.  Thanks!

**Comment by Coacher** [comment]
Hello again.

Thank you for your awesome quick and nice responses!

Unfortunately, my previous pull request contains one unattended and unwanted side-effect: it breaks Visual mode yanks/pastes near blank lines. Let me demonstrate this by example.

Consider the following file:
```
line one
line two

line three
```

Now use `Vjy` to yank the first two lines. Then again select these lines via `Vj` and paste using `p` or `P`. The resulting file is:
```

line one
line two
line three
```

Note that the blank line is now first. Expected results are:
```
line one
line two

line three
```

This problem happens due to the column check that was introduced in my previous pull request.
It does not work properly with blank lines. With blank lines we have `col('.') == col('$') == 1`. And after `normal! "_d` on the selected lines, we are sitting on a blank line. This leads to inappropriate operation being selected. Full and proper column check should be `(col('.') < col('$') - 1 || col('$') == 1)`.

But wait there's more.. see below.

**Comment by Coacher** [comment]
After revisiting my changes I noticed that position checks after `normal! "_d` do not make much sense and lead to problems. For example, if we are sitting on the last line we always do pasting after it. This is wrong if we paste over the first two lines in such file:
```
line one
line two
line three
```
Same example can be constructed for last column. The proper solution would be to do position checks before  `normal! "_d`.

**Comment by Coacher** [comment]
In fact proper column check is a bit more complicated:
`(col('.') < col('$') - 1 || col('$') <= 2)`

It has to be this way as when line is one character long and we've selected the only (and the last) character in this line `col('.') < col('$') - 1` will still give us `False`.

**Comment by Coacher** [comment]
This is how it should be done in the first place. These changes should be the final fix for Visual mode paste. I cannot reproduce old problems with pasting over the last line(s) or column(s) and new ones, which I've discussed just above.

Sorry for any inconvenience my initial changes have caused.

**Comment by svermeulen** [comment]
Hey, thanks for following up on this!  I actually noticed a few of these issues and was meaning to look into it at some point.
