### ISSUE TITLE
"let g:EasyClipPreserveCursorPositionAfterYank = 1" has no effect

### ISSUE THREAD

**Issue by maikelmeyers** [svermeulen/vim-easyclip#53]
let g:EasyClipPreserveCursorPositionAfterYank = 1
in my vimrc does not change the behavior of the cursor when yanking. If I select some lines in visual mode from up to down and press y, the cursor still moves to the beginning of the yanked text.

**Comment by svermeulen** [comment]
Ah good point.  This flag only preserves the position of the cursor when in normal mode.  It should also apply in visual mode.

**Comment by svermeulen** [comment]
I've fixed this issue on the develop branch.  Going to way a few days then merge it into master.

**Comment by maikelmeyers** [comment]
Many Thanks! Very fast! :)

**Comment by svermeulen** [comment]
No problem - let me know if you catch any other issues
