### ISSUE TITLE
I find `<c-p>` unusual in instructions

### ISSUE THREAD

**Issue by wolftune** [svermeulen/vim-easyclip#57]
I am sure it's used somewhere, but I struggled to understand what `<c-p>` meant as a command. I am much more used to seeing Ctrl-P (usuablly not as a code block, but maybe). I am not an expert vim user, and maybe these are more common syntax, but I've used a lot of plugins and other things, and this is the first I came upon that. It would be nice to at least clarify what that means in the docs, imho.

Btw, thanks so much, love this fix to actually have real clipboard behavior!

**Comment by svermeulen** [comment]
`<c-p>` is how the mapping looks when mapping the key in Vim.  But I can see how that might be confusing if you don't edit a lot of vimscript yourself.  I'll clarify that.

No problem, glad you are enjoying it  :)
