### ISSUE TITLE
Slow line yank after latest update

### ISSUE THREAD

**Issue by Alok** [svermeulen/vim-easyclip#58]
Hey,

I updated to the latest commit yesterday, and since then, the 'yy' command specifically has been unusably slow. I can yank anything, even the same text (e.g. at the beginning of a line using y$) just fine, but I can't use 'yy' specifically. 

Uninstalling easyclip fixed it, but on reinstall the issue was back. I notice that the latest changes were to the Yanks file, so maybe something is up there, like a recursive mapping getting repeatedly called.

**Comment by svermeulen** [comment]
I'm not experiencing any issue and am not seeing any red flags in the recent history.  Can you try reproducing it using vanilla vim with a minimal vimrc?

What easy clip options are you using?  Are you using shared clipboard?  What platform?  What was the previous version that you were using that worked?

**Comment by Alok** [comment]
I tried it with a minimal vimrc in vanilla and it didn't appear. Also, it works fine now, so I think it's probably some weird one-off interaction with something else on my system.
