### ISSUE TITLE
Make Yanks window interactive

### ISSUE THREAD

**Issue by sassanh** [svermeulen/vim-easyclip#61]
I was using YankRing and now I installed easyclip and am totally satisfied with its functionality, except its Yanks window. It'd be great if the Yanks window could get interactive like YankRing.
If that's hard and takes time, it'd be great if user could enter the yank number shown on Yanks window and specified yank gets pasted. This is required because I can easily paste yank number 0-9 with registers but I can't paste yank number 24 for example, I open the Yanks window, I see my yank is at number 24 but I can't reach it with some easy shortcuts.

**Comment by svermeulen** [comment]
Yeah I agree this would be nice.  Like you say, sometimes the yank you want is so far back in the yank buffer that it's a pain to toggle to.  I'll try to find some time to look a look at something like this.

**Comment by svermeulen** [comment]
Ok I went with your suggestion of just simply entering the yank number after reading the Yanks popup
Execute `:IPaste` (aka interactive paste) then enter the index to paste from.

**Comment by sassanh** [comment]
@svermeulen thanks :+1:
