### ISSUE TITLE
pum completion plugin help

### ISSUE THREAD

**Issue by davidosomething** [svermeulen/vim-easyclip#63]
I made a plugin that works with EasyClip registers with some help from rgvim here:

https://github.com/davidosomething/EasyClipRing.vim

When I'm retrieving a multi-line yank, I get a bunch of null characters where newlines should be,
any advice on how to clear those up?

**Comment by svermeulen** [comment]
Cool plugin!

I'm not sure what null characters you're seeing.  As far as I can tell, multi-line yanks just contain newlines as you would expect.  Can you provide me with an easy way to reproduce the issue you're seeing?

**Comment by davidosomething** [comment]
managed to fix it with some help on reddit, the substitute line here does the trick

https://github.com/davidosomething/EasyClipRing.vim/blob/master/autoload/EasyClipRing.vim#L37

**Comment by svermeulen** [comment]
Oh ok cool.
