### ISSUE TITLE
Shared Yanks overwrites first yank

### ISSUE THREAD

**Issue by somini** [svermeulen/vim-easyclip#64]
First of all, thanks for this plugin, it makes the vim clipboard sane to use.

If you have Shared Yanks enabled, when Vim starts up it will read the file and populates the yanks. The problem is that the current clipboard contents disappear.

It's easy to reproduce:
- With vim closed, copy some text into the clipboard.
- Open vim
- Paste

It should have pasted the text you copied before, but it actually pastes the last yank from the file. To add insult to injury, it also overwrites the clipboard, so the text you copied is now gone forever.

**Comment by svermeulen** [comment]
Hey thanks for the report.  I don't use shared yanks on my system which is why I would not have noticed this issue.  I'll take a look at this.

**Comment by svermeulen** [comment]
Ok I committed a fix for it.  Can you update and verify that it works how you expect?

**Comment by somini** [comment]
Yes, commit 9715012aefe30ddd2951d2e3f80b22b43c56521a fixed this issue.

Thanks for the quick response.
