### ISSUE TITLE
map M to move to end line does not work

### ISSUE THREAD

**Issue by lookforit** [svermeulen/vim-easyclip#65]
Hi,
I use the latest version ,and set 
```vim
nmap M <Plug>MoveMotionEndOfLinePlug
```
When I pressed M(uppercase),nothing happens,why?
If I run `:map`,I can get the following about `M`:
```vim
s  M           * <C-O>"_cM
n  M             <Plug>MoveMotionEndOfinePlug
```

Any help?

**Comment by svermeulen** [comment]
I tried your mapping in a clean install of vim + easy clip and it seems to work as expected to me.  It cuts text from the cursor to the end of the current line.  Do you still get it with a stripped down vimrc?

**Comment by sassanh** [comment]
@lookforit if you have copied above lines from vim, you have a tipo in your map, it should be MoveMotionEndOfLinePlug not MoveMotionEndOfinePlug (notice the missing L in the beginning of Line)

**Comment by svermeulen** [comment]
Oh yeah good catch, that was likely the problem here.
