### ISSUE TITLE
unnamed ("") register being populated

### ISSUE THREAD

**Issue by fdelacruz** [svermeulen/vim-easyclip#67]
The following `d{motion}, dd, D, c{motion}, cc, C, s, and S`
All populate the unnamed ("") register.
I have tested it with: 
`:command! RegClear :let @a='' | let @-='' | let @0='' | let @1='' | let @"=''`
Which then I can use to clear the "a, "-, "0, "1 and the "" registers by issuing `:RegClear`.
Checking the content of the registers `:reg` after each of the aforementioned vim commands.
I'm on OS X (SL)
vim 
clipboard=unnamed

**Comment by svermeulen** [comment]
So hitting `dd` will save the current line to the unnamed register?  I just ran a test with vanilla vim and this worked ok on windows, so I wonder if this is a mac thing.

**Comment by fdelacruz** [comment]
Yes.
Can any other Mac users test this??
On Mon, Dec 7, 2015 at 3:00 PM Steve Vermeulen <notifications@github.com>
wrote:

> So hitting dd will save the current line to the unnamed register? I just
> ran a test with vanilla vim and this worked ok on windows, so I wonder if
> this is a mac thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/svermeulen/vim-easyclip/issues/67#issuecomment-162643387>
> .
>
-- 
Warm regards,
Francisco De La Cruz
(646)294-2547

Sent from my IPhone

**Comment by fdelacruz** [comment]
How did you go about testing it in a vanilla vim. My guess is start vim
without loading plugins and then load easyclip. Can you please go over
that?? Thank you

On Mon, Dec 7, 2015 at 3:26 PM Francisco De La Cruz <helloquico@gmail.com>
wrote:

> Yes.
> Can any other Mac users test this??
> On Mon, Dec 7, 2015 at 3:00 PM Steve Vermeulen <notifications@github.com>
> wrote:
>
>> So hitting dd will save the current line to the unnamed register? I just
>> ran a test with vanilla vim and this worked ok on windows, so I wonder if
>> this is a mac thing.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/svermeulen/vim-easyclip/issues/67#issuecomment-162643387>
>> .
>>
> --
> Warm regards,
> Francisco De La Cruz
> (646)294-2547
>
> Sent from my IPhone
>
-- 
Warm regards,
Francisco De La Cruz
(646)294-2547

Sent from my IPhone

**Comment by fdelacruz** [comment]
I should maybe add that I'm using the following settings:

>let g:EasyClipUseSubstituteDefaults = 1

>let g:EasyClipUseCutDefaults = 0
>nmap x <Plug>MoveMotionPlug
>xmap x <Plug>MoveMotionXPlug
>nmap xx <Plug>MoveMotionLinePlug

>let g:EasyClipUsePasteToggleDefaults = 0
>nmap <c-f> <plug>EasyClipSwapPasteForward
>nmap <c-d> <plug>EasyClipSwapPasteBackwards

**Comment by fdelacruz** [comment]
Oops!!

**Comment by svermeulen** [comment]
For testing these kinds of things I use a stripped down vimrc that just contains the following.  Then I run it by executing `gvim.exe -u ~/.vimrc2`.  I append a 2 to vimrc and also the vim directory to allow me to avoid changing my normal config

    " Note: Skip initialization for vim-tiny or vim-small.
    if !1 | finish | endif

    let &rtp = substitute(&rtp, 'Steve/vimfiles\>', 'Steve/vimfiles2', 'g')
    let &rtp = substitute(&rtp, 'Steve/.vim\>', 'Steve/.vim2', 'g')

    if has('vim_starting')
        set nocompatible               " Be iMproved

        " Required:
        set runtimepath+=~/.vim2/bundle/neobundle.vim/
    endif

    " Required:
    call neobundle#begin(expand('~/.vim2/bundle/'))

    " Let NeoBundle manage NeoBundle
    " Required:
    NeoBundleFetch 'Shougo/neobundle.vim'

    NeoBundle 'svermeulen/vim-easyclip.git'

    NeoBundle 'tpope/vim-repeat'

    call neobundle#end()

    " Required:
    filetype plugin indent on

    " If there are uninstalled bundles found on startup,
    " this will conveniently prompt you to install them.
    NeoBundleCheck

    """""""""""""""""""""""
    " Settings
    """""""""""""""""""""""

    set clipboard=unnamed

**Comment by svermeulen** [comment]
By the way, that vimrc is just taken from the neobundle page.

Unfortunately I don't have a mac so can't try and reproduce this. Can you try it with a similarly stripped down config?

**Comment by fdelacruz** [comment]
I'm on it..

**Comment by fdelacruz** [comment]
Did something similar to what you did and used the striped down vimrc found in the Vundle repo.
The unnamed register still gets populated on deletes.

**Comment by svermeulen** [comment]
I'll see if I can figure out a way to reproduce this on mac.  I can't really fix it otherwise

**Comment by fdelacruz** [comment]
Thanks for looking into this. I'm surprised no other Mac user has noticed this. I hope it's not just me.

**Comment by fdelacruz** [comment]
I'm starting to think this is a very serious vim bug. 
Even manually remapping d to "_d this issue persists `:nnoremap d "_d`

**Comment by svermeulen** [comment]
Oh interesting.  The black hole register doesn't work at all?  What if you just type "_d instead of using a mapping?

**Comment by fdelacruz** [comment]
Yes, without using a mapping the black hole register seems to work.

**Comment by fdelacruz** [comment]
I think I found the problem.
Somehow jshint is hijacking dw and dd:
![jshint_vs_easyclip](https://cloud.githubusercontent.com/assets/148098/11647967/8cec3716-9d3c-11e5-9baa-fc64193900ea.png)

The thing is, I already uninstalled both the vim plugin and the npm package.

**Comment by svermeulen** [comment]
Ah yes.  That makes more sense than a vim bug or easyclip completely not working on mac  :)

**Comment by fdelacruz** [comment]
That's for sure!!
