### ISSUE TITLE
Yank doesn't work with Text Objects correctly

### ISSUE THREAD

**Issue by dbelikov** [svermeulen/vim-easyclip#79]
After installing the plug-in, yank no longer correctly copies using text objects.
E.g. yiw is supposed to yank the current word. yi( everything within parenthesis, etc. None of this combinations work with vim-easyclip.

**Comment by svermeulen** [comment]
This should work.  When you say they don't work you mean they do nothing?  What platform?

**Comment by dbelikov** [comment]
Oh, you're right. I just tried it on a clean ubuntu instance with just Vundle, vim-repeat and vim-easyclip and yank performed all operations correctly. Apparently some of my other plugins or some settings interfered with yank.

Thank you for your response!

**Comment by svermeulen** [comment]
Ok, glad you got it working.
