### ISSUE TITLE
Remapping adding mark

### ISSUE THREAD

**Issue by idurandiaz** [svermeulen/vim-easyclip#82]
Hi,

I just installed your plugin and everything seems to be working fine, except that I tried to remap `m` as you suggest with `nnoremap gm m`, however this is not working for me (marks are not being set). If I use your other suggestion by setting `let g:EasyClipUseCutDefaults = 0` and remapping to `x` (e.g. `nmap x <Plug>MoveMotionPlug`), it does work I regain usage of `m` to add marks. However I prefer the first option as I am used to using `x` to delete characters. Any idea why the first option/suggestion is not working (that is, `nnoremap gm m`)? I tried different mapping options instead of `gm` but none of them have worked so far.

**Comment by idurandiaz** [comment]
Sorry, I found what the problem was (some how there was an extra space after `m` in `noremap gm m`). No it is working properly. Thanks for the great plugin

**Comment by svermeulen** [comment]
No problem.  Glad you got it working.
