### ISSUE TITLE
D still overwrites the yank register

### ISSUE THREAD

**Issue by Skyfold** [svermeulen/vim-easyclip#83]
although d <motion> writes to the black hole register, D still overwrites ""

**Comment by svermeulen** [comment]
`D` writes to the black hole register correctly on my machine.  

I just tested this by using vanilla vim + easyclip + repeat.vim.  Can you confirm this by trying it with vanilla vim as well?  (To ensure it's not a conflict with another plugin)

**Comment by Skyfold** [comment]
I should have tested this using vanilla vim + easyclip. My sincere apologies.

 I will try and see if I can figure out what was the conflicting plugin.

**Comment by svermeulen** [comment]
No problem
