### ISSUE TITLE
Conflict with vim-gtfo?

### ISSUE THREAD

**Issue by srsudar** [svermeulen/vim-easyclip#88]
I am trying to install [vim-gtfo](https://github.com/justinmk/vim-gtfo), which provides `:got` and `:gof`. `:gof` doesn't work, claiming it's not an editor command. Following the author's advice of running `:verbose map gof`, it looks like `vim-easyclip` might be to blame. I don't understand vimscript or the output of this command well enough to know what is going on:

```
n  gof         * :<C-U>call gtfo#open#file("%:p")<CR>
        Last set from ~/dotfiles/vim/plugged/vim-gtfo/plugin/gtfo.vim
s  g           * <C-O>"_cg
        Last set from ~/dotfiles/vim/plugged/vim-easyclip/autoload/EasyClip/BlackHole.vim
```

Does this look like a real conflict? Any ideas about what it's doing or how to resolve it?

**Comment by svermeulen** [comment]
easy-clip is overriding the "g" mapping in select mode there (you can see this by the 's' character next to it).  This shouldn't affect the gof command which is in normal mode (shown by the 'n' character').

So to me it doesn't seem like easy-clip is related.

**Comment by srsudar** [comment]
Turns out I'm a doofus. It is indeed a normal mode command, thus it's `gof` not `:gof`. At least I'm [not the first](https://github.com/justinmk/vim-gtfo/issues/33). Sorry for the spam.
