### ISSUE TITLE
the 's' motion sometimes behaves strangely

### ISSUE THREAD

**Issue by timfeirg** [svermeulen/vim-easyclip#92]
when you are near the end of file (the line above the last line), the `s` motion would act differently:

assume you have some multiline text inside the default register

```
here is the first line, it should be preserved
and the second line, I'll substitute the last two line with the text inside register [cursor]
the third line
```

and then press `sk`, the text will become...

```
this is the multi line
inside the register
here is the first line, it should be preserved
```

the first line have been moved to the last, but if there's a new line below the original text, the `s` motion would then behave as expected

**Comment by proever** [comment]
I can reproduce this on the latest release of EasyClip.

Starting with
```
here is the first line, it should be preserved
and the second line, I'll substitute the last two line with the text inside register [cursor]
the third line
and a fourth
```
and
```
this is the multi line
inside the register
```
on my default register, pressing `sk` on line 3 produces
```
here is the first line, it should be preserved
this is the multi line
inside the register
and a fourth
```
but if I start with
```
here is the first line, it should be preserved
this is the multi line
inside the register
```
and press `sk` on line 3, I get
```
this is the multi line
inside the register
here is the first line, it should be preserved
```
