### ISSUE TITLE
MoveMotionReplaceLinePlug vs MoveMotionLinePlug

### ISSUE THREAD

**Issue by matrinox** [svermeulen/vim-easyclip#97]
First of all, the name suggests replace but really it's just cut. Second, MoveMotionLinePlug does everything that MoveMotionReplaceLinePlug does but also supports count. What's the usefulness for MoveMotionReplaceLinePlug?

**Comment by svermeulen** [comment]
I think you'll want to use `MoveMotionEndOfLinePlug`.  The only difference is that `MoveMotionReplaceLinePlug` does not cut the new line character (just the contents of the line).

I agree that the name is terrible, but it's too late to change since people might be using it.

**Comment by matrinox** [comment]
Yeah, that's the problem with making an interface public. Thanks for clarifying the really minor difference lol
