### ISSUE TITLE
Issue with install

### ISSUE THREAD

**Issue by kirkins** [svermeulen/vim-easyclip#98]
I'm using vundle and this is one of the first plugins I'm installing.

I added:

    Plugin 'tpope/vim-repeat'
    Plugin 'vim-easyclip'

To my `~/.vimrc `and then ran `:PluginInstall `from inside vim. It said it worked but I'm running two new instances of vim split screen and each seems to have a seperate buffer when I use yank.

Any ideas on how I can debug?

**Comment by kirkins** [comment]
Ok I've read over the README and see that I need to enable:

    g:EasyClipShareYanks 

Where to I input this? I did` :g:EasyClipShareYanks `from inside a vim file but it said pattern not found.

**Comment by svermeulen** [comment]
Hey, sorry for the late response.  

You can enable shared yanks by including this in your .vimrc:
```
let g:EasyClipShareYanks = 1
```
